import { ArticlesProvider } from "@/context/ArticlesContext";
import { UserProvider } from "@/context/UserContext";
import Header from "@/ui/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <UserProvider>
            <ArticlesProvider>
              <Header />
              <main>{children}</main>
            </ArticlesProvider>
          </UserProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
